house/urls.py
from django.urls import path
# from django.views.generic import TemplateView
from house.views import (IndexView, HomeView, LoginView, LogoutView, AddRecordView, EditRecordView,
                         EditTitleView, AddRoomView, RoomView, AddPurchaseView)
from . import views

app_name = 'house'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('house/', HomeView.as_view(), name='house'),
    path('room/add', AddRoomView.as_view(), name='add_room'),
    path('room/<room_id>/', RoomView.as_view(), name='room'),
    path('room/<room_id>/new/purchase', AddPurchaseView.as_view(), name='new_device'),
    path('record/add/', AddRecordView.as_view(), name='add_record'),
    path('record/delete/', views.delete_record, name='delete_record'),
    path('record/edit/', EditRecordView.as_view(), name='edit_record'),
    path('title/edit/', EditTitleView.as_view(), name='edit_title'),
]

house/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from house.models import House, Room, Device, Repair, Maintenance, MaintenanceEvent, Record, BaseName


generic_error = 'There was an error with your request. Please refresh the page and try again.'


class ContentTypeField(forms.Field):
    @staticmethod
    def get_content_type(value):
        object_types = {
            'house': House,
            'room': Room,
            'device': Device,
            'repair': Repair,
            'maintenance': Maintenance,
            'maintenanceEvent': MaintenanceEvent
        }
        return object_types.get(value)

    def to_python(self, value):
        return self.get_content_type(value)

    def validate(self, value):
        if not value:
            raise ValidationError(
                (generic_error),
                params={'value': value},
            )


class BaseObjectForm(forms.Form):
    name = forms.CharField(
        label='Name',
        widget=forms.TextInput,
        max_length=50,
        min_length=1)

    name.widget.attrs.update({
        'class': 'form-control'})

    date = forms.DateField(
        input_formats=['%m/%d/%Y'],
        widget=forms.DateInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )

    # date.widget.attrs.update({
    #     'class': 'input-group date col-sm-10',
    #     'id': 'datetimepicker1',
    #     'data-target-input': 'nearest'
    # })

    warrenty_length = forms.CharField(
        label='Warrenty Length',
        widget=forms.TextInput,
        max_length=150,
        min_length=1)

    warrenty_length.widget.attrs.update({
        'class': 'form-control',
        'placeholder': '1 Year'})

    cost = forms.IntegerField(
        label='Cost',
        widget=forms.NumberInput
    )

    cost.widget.attrs.update({
        'placeholder': '$100',
        'class': 'form-control'})

    notes = forms.CharField(
        label='Notes',
        widget=forms.Textarea,
        max_length=1000,
        min_length=1
    )

    notes.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Additional notes....'})


class AddDeviceForm(BaseObjectForm):
    field_order = ['name', 'date', 'cost', 'purchase_from', 'warrenty_length', 'notes']

    purchase_from = forms.CharField(
        label='Store',
        widget=forms.TextInput)

    purchase_from.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Amazon'})


class EditTitleForm(forms.ModelForm):
    object_type = ContentTypeField()
    object_id = forms.UUIDField()

    class Meta:
        model = BaseName
        fields = ['name', 'object_id', 'object_type']
        error_messages = {
            'name': {
                'max_length': ("Names are limited to 50 characters."),
                'required': 'A name is required.',
            },
            'object_id': {
                'invalid': generic_error
            }
        }


class AddRecordForm(forms.ModelForm):
    object_type = ContentTypeField()

    class Meta:
        model = Record
        fields = ['statement', 'response', 'object_id', 'object_type']
        error_messages = {
            'statement': {
                'max_length': ("Statments are limited to 150 characters."),
                'required': 'A statement is required for each record.',
            },
            'response': {
                'max_length': 'Responses are limited to 150 characters.'
            },
            'object_id': {
                'invalid': generic_error
            }
        }


class EditRecordForm(forms.ModelForm):
    record_id = forms.UUIDField()

    class Meta:
        model = Record
        fields = ['statement', 'response', 'record_id']
        error_messages = {
            'statement': {
                'max_length': ("Statments are limited to 150 characters."),
                'required': 'A statement is required for each record.',
            },
            'response': {
                'max_length': 'Responses are limited to 150 characters.'
            },
            'record_id': {
                'invalid': generic_error
            }
        }


class SignUpForm(forms.Form):
    def validate_password(value):
        if len(value) < 8:
            raise ValidationError(
                ('Password must be at least 8 characters long.'),
                params={'value': value},
            )

    def validate_email(email):
        e = User.objects.filter(email=email).exists()
        if e:
            raise ValidationError(
                ('That email has already been registered.'),
                params={'email': email},
            )

    email = forms.EmailField(
        label='Email',
        validators=[validate_email],
        widget=forms.EmailInput)

    password = forms.CharField(
        label='Password',
        max_length=100,
        validators=[validate_password],
        widget=forms.PasswordInput)

    email.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Email'})
    password.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Password'})

    def create_user(self):
        user = User.objects.create_user(
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'])
        House.objects.create(
            owner=user,
            name='Your House',
        )


class AuthForm(forms.Form):
    email = forms.CharField(
        label='Username/Email',
        widget=forms.TextInput)
    password = forms.CharField(
        label='Password',
        max_length=100,
        widget=forms.PasswordInput)

    email.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Username/Email'})
    password.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Password'})


class AddRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['name']
        error_messages = {
            'statement': {
                'max_length': ("Room names are limited to 50 characters."),
                'required': 'A name is required for each room.',
            }
        }

house/views/house.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core import serializers

from house.models import House, Record, Room
from house.forms import AddRoomForm
from house.utils import get_records


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/house.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        house = House.objects.filter(owner=self.request.user).first()
        data['house'] = house
        records = get_records(self.request.user, house.id, 'house')
        data['records'] = records
        return data

house/views/misc.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import FormView

from house.forms import EditTitleForm
from house.models import BaseName
from house.mixins import AjaxResponseMixin


class EditTitleView(AjaxResponseMixin, FormView):
    model = BaseName
    form_class = EditTitleForm

    def form_valid(self, form):
        print('did validate')
        try:
            object = get_object_or_404(
                form.cleaned_data['object_type'],
                pk=form.cleaned_data['object_id'],
                owner=self.request.user)
            object.name = form.cleaned_data['name']
            object.save()
            return HttpResponse(status=204)
        except:
            error_message = ['There was an error editing this name, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)

house/views/record.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView

from house.forms import AddRecordForm, EditRecordForm
from house.models import Record
from house.mixins import AjaxResponseMixin


# TODO: Find way to add LoginRequiredMixin back without redirect
class EditRecordView(AjaxResponseMixin, FormView):
    model = Record
    form_class = EditRecordForm

    def form_valid(self, form):
        try:
            r = get_object_or_404(
                Record,
                pk=form.cleaned_data['record_id'],
                owner=self.request.user)
        except:
            error_message = ['There was an error editing this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)
        r.statement = form.cleaned_data['statement']
        r.response = form.cleaned_data['response']
        r.save()
        return HttpResponse(status=204)


@login_required
def delete_record(request):
    if request.method == 'POST':
        record_id = request.POST.get('record_id')
        try:
            record = get_object_or_404(Record, owner=request.user, id=record_id)
            record.delete()
            return HttpResponse(status=204)
        except:
            error_message = [
                'There was an error deleting this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)


class AddRecordView(AjaxResponseMixin, FormView):
    model = Record
    form_class = AddRecordForm

    def form_valid(self, form):
        try:
            obj = get_object_or_404(
                form.cleaned_data['object_type'],
                pk=form.cleaned_data['object_id'],
                owner=self.request.user)
        except:
            error_message = [
                'There was an error creating this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)
        record = Record.objects.create(
            owner=self.request.user,
            statement=form.cleaned_data['statement'],
            content_object=obj
        )
        if form.cleaned_data.get('response'):
            record.response = form.cleaned_data['response']
        record.save()
        data = {'id': record.id}
        return JsonResponse(data)

house/views/room.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.contenttypes.models import ContentType
# from django.contrib import messages

from house.models import House, Room, Repair, Device, Maintenance
from house.forms import AddRoomForm, AddDeviceForm
from house.utils import get_records

from itertools import chain


class RoomView(LoginRequiredMixin, TemplateView):
    template_name = 'house/page/room.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        room_id = self.kwargs.get('room_id')
        room = Room.objects.filter(owner=self.request.user, id=room_id).first()
        records = get_records(self.request.user, room.id, 'room')
        data['room'] = room
        data['records'] = records
        repairs = Repair.objects.filter(owner=self.request.user, room=room).order_by("date").all()
        devices = Device.objects.filter(owner=self.request.user, room=room).all()
        maintenance = Maintenance.objects.filter(owner=self.request.user, room=room).all()
        objects = list(chain(repairs, devices, maintenance))
        objects = sorted(objects, key=lambda o: o.date)
        data['objects'] = objects
        return data


class AddRoomView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/all_rooms.html'
    model = Room
    form_class = AddRoomForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        rooms = Room.objects.filter(owner=self.request.user).all()
        rooms.order_by('name')
        data['rooms'] = rooms
        return data

    def form_valid(self, form):
        name = form.cleaned_data['name']
        house = House.objects.filter(owner=self.request.user).first()
        r = Room.objects.create(name=name, house=house, owner=self.request.user)
        return redirect(reverse('house:room', args=[r.id]))


class AddPurchaseView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/new_device.html'
    model = Device
    form_class = AddDeviceForm

    def get_context_data(self, **kwargs):
        # TODO: handle case where no room is found
        data = super().get_context_data(**kwargs)
        room = Room.objects.filter(owner=self.request.user).filter(id=self.kwargs['room_id']).first()
        data['room'] = room
        return data

    def form_valid(self, form):
        print('valid form')
        room = Room.objects.filter(owner=self.request.user).filter(id=self.kwargs['room_id']).first()
        device = Device(name=form.cleaned_data['name'],
                        room=room,
                        date=form.cleaned_data['date'],
                        warrenty_length=form.cleaned_data['warrenty_length'],
                        cost=form.cleaned_data['cost'],
                        notes=form.cleaned_data['notes'],
                        owner=self.request.user)
        device.save()
        return redirect(reverse('house:room', args=[room.id]))

    def form_invalid(self, form):
        print('form invalid')
        print(form['date'])
        return super(AddPurchaseView, self).form_invalid(form)













#

house/views/user.py
from django.shortcuts import render
from django.views.generic import FormView, RedirectView
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

from house.forms import SignUpForm, AuthForm


class IndexView(FormView):
    template_name = 'house/page/index.html'
    form_class = SignUpForm
    success_url = reverse_lazy('house:house')

    def form_valid(self, form):
        form.create_user()
        user = User.objects.filter(email=form.cleaned_data['email']).first()
        login(self.request, user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'house/page/login.html'
    form_class = AuthForm
    success_url = reverse_lazy('house:house')

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('house:house'))
        else:
            form = AuthForm
            return render(request, 'house/page/login.html', {'form': form})

    def form_valid(self, form):
        username = form.cleaned_data['email']
        if '@' in form.cleaned_data['email']:
            user = User.objects.filter(
                email=form.cleaned_data['email']).first()
            username = user.username
        user = authenticate(
            username=username,
            password=form.cleaned_data['password'])
        if user is None:
            messages.info(self.request, 'Invalid email/password')
            return render(self.request, 'house/page/login.html', {'form': form})
        else:
            login(self.request, user)
            return super().form_valid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('house:login')

    def get(self, request):
        url = self.get_redirect_url()
        logout(request)
        messages.info(self.request, 'You have been logged out')
        return HttpResponseRedirect(url)

house/templates/house/fragment/basic_title.html
{% load static %}
<div class="container-fluid">
    <div class="row">
        <h1 id="page-title">{{title}}</h1>
    </div>
</div>

house/templates/house/fragment/card.html
<div class="card card-card">
    <div class="card-body">
    <h5 class="card-title">{{object.name}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{object.date}}</h6>
    <p class="card-text">{{object.notes}}</p>
    <a href="#" class="card-link">Records</a>
    <a href="#" class="card-link">Reminders</a>
    </div>
</div>

house/templates/house/fragment/card_group.html
<div class="card">
    <div class="card-header" id="heading-{{name}}">
        <h5 class="mb-0">
            <div class="container-fluid">
                <div class="row">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-{{name}}" aria-expanded="false" aria-controls="collapse-{{name}}" style="padding-right:5px;">
                        <h4>{{name}}</h4>
                    </button>
                    <a href="#" class="mt-auto" data-toggle="modal" data-target="#newDeviceModal">
                        <i class="far fa-plus-square card-group-plus-icon"></i>
                    </a>
                </div>
            </div>
        </h5>
    </div>

    <div id="collapse-{{name}}" class="collapse" aria-labelledby="heading-{{name}}" data-parent="#accordion">
        {% if objects %}
            <div class="card-body">
                <div class="row" id="card-row">
                    {% for object in objects %}
                        {% include "house/fragment/card.html" with object=object %}
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <h5 class="card-group-no-cards-yet">No {{name}} yet.</h5>
        {% endif %}
    </div>
</div>

house/templates/house/fragment/edit_title.html
{% load static %}
<div class="container-fluid">
    <div class="row">
        <h1 id="page-title">{{title}}</h1>
        <a href="#" class="mt-auto" data-toggle="modal" data-target="#edit-title-modal">
            <i class="far fa-edit edit-title-edit-icon"></i>
        </a>

    </div>
</div>

<!-- Edit Title Modal -->
<div class="modal fade" id="edit-title-modal" tabindex="-1" role="dialog" aria-labelledby="edit-title-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit-title-modal-label">Edit Name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id='edit-title-modal-body' class="modal-body">
                <form id="record-form">
                    <div class="form-group">
                        <input
                            type="text"
                            id='edit-title-new-name'
                            name="name"
                            id='edit-page-name'
                            class="form-control"
                            value='{{title}}'
                        >
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id='edit-title-save' class="btn btn-primary" onclick="edit_title('{{id}}', '{{object_type}}')">Save</button>
            </div>
        </div>
    </div>
</div>

house/templates/house/fragment/event_form.html
<form method="POST">
    {{form.errors}}
    {% for field in form %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{field.label}}</label>
            {% if field.label == 'Date' %}
                <div class="input-group date col-sm-10 col-md-8 col-lg-6" id="datetimepicker4" data-target-input="nearest">
                    {{ field }}
                    <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-10 col-md-8 col-lg-6">
                  {{field}}
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
          <button class="btn btn-primary">Save</button>
        </div>
    </div>
    {% csrf_token %}
</form>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker4').datetimepicker({
            format: 'L'
        });
    });
</script>

house/templates/house/fragment/record.html
{% load static %}
<link rel="stylesheet" href="{% static "css/pages/add_records.css" %}">

<h4>Records</h4>
<div class="col-md-8">
    <table id='record-table' class="table table-sm table-bordered">
        <tbody id='record-table-tbody'>

        </tbody>
    </table>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Record</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id='delete-record-modal-body' class="modal-body">
                <p>
                    <strong>Are you sure you want to delete this record?</strong>
                </p>
                <p id='deleteModalBody'></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" id='confirm-delete-record' class="btn btn-danger">Delete Record</button>
            </div>
        </div>
    </div>
</div>

<!-- Add Record -->
<button type="button" class="btn btn-primary" onclick="add_record('{{object_id}}', '{{object_type}}')">
    Add Record
</button>


<div class="modal fade" id="add-record-modal" tabindex="-1" role="dialog" aria-labelledby="addRecordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addRecordModalLabel">Add/Edit Record</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id='add-record-modal-body' class="modal-body">
                <form id="record-form">
                    <div class="form-group">
                        <label>Statement</label>
                        <input
                            type="text"
                            name="statement"
                            id='add-record-statement'
                            class="form-control"
                            placeholder="Year house was built"
                        >
                    </div>
                    <div class="form-group">
                        <label>Response</label>
                        <input
                            type="text"
                            name="response"
                            id='add-record-response'
                            class="form-control"
                            placeholder="1998"
                        >
                    </div>
                    {% csrf_token %}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Canel</button>
                <button type="submit" id='add-record' class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

house/templates/house/fragment/signup_base.html
{% load static %}
<nav class="navbar navbar-light navbar-expand bg-light navigation-clean">
    <div class="container"><a class="navbar-brand" href="#">Welcome to BlueBoard</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            {% if sign_up %}
                <a class="btn btn-primary ml-auto" role="button" href="{% url 'house:login' %}">Login</a>
            {% else %}
                <a class="btn btn-primary ml-auto" role="button" href="{% url 'house:index' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</nav>

<div id="index-img" class="container-fluid text-center" style="background:transparent url('{% static "img/bg-masthead.jpg" %}') no-repeat center center /cover">
    {% if form.username.errors %}
        <div class="alert alert-primary" role="alert">
            {{form.username.errors.as_text}}
        </div>
    {% endif %}
    {% if form.email.errors %}
        <div class="alert alert-primary" role="alert">
            ee{{form.email.errors.as_text}}
        </div>
    {% endif %}
    {% if form.password.errors %}
        <div class="alert alert-primary" role="alert">
            {{form.password.errors.as_text}}
        </div>
    {% endif %}
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-primary" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
    {% endif %}
    <div class="row" >
        {% if sign_up %}
            <h1 id="tagline" class="container-fluid">Home management made easy</h1>
        {% else %}
            <h1 id="tagline" class="container-fluid">Please login to continue</h1>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-6 offset-sm-3 text-center">
            <div class="info-form">
                <form method="POST" class="form-inlin justify-content-center">
                    {% for field in form %}
                        <div class="form-group">
                            {{field}}
                        </div>
                    {% endfor %}
                    {% if sign_up %}
                        <button class="btn btn-lg btn-primary" onclick="showToast()">Sign Up</button>
                    {% else %}
                        <button class="btn btn-lg btn-primary" onclick="showToast()">Login</button>
                    {% endif %}
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>

house/templates/house/fragment/simple_title.html
{% load static %}
<div class="container-fluid">
    <div class="row">
        <h1 id="page-title">{{title}}</h1>
    </div>
</div>