house/urls.py
from django.urls import path
# from django.views.generic import TemplateView
from house.views import (IndexView, HomeView, LoginView, LogoutView, AddRecordView, EditRecordView,
                         EditTitleView, AddRoomView, RoomView, AddPurchaseView)
from . import views

app_name = 'house'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('house/', HomeView.as_view(), name='house'),
    path('room/add', AddRoomView.as_view(), name='add_room'),
    path('room/<room_id>/', RoomView.as_view(), name='room'),
    path('room/<room_id>/new/purchase', AddPurchaseView.as_view(), name='new_device'),
    path('record/add/', AddRecordView.as_view(), name='add_record'),
    path('record/delete/', views.delete_record, name='delete_record'),
    path('record/edit/', EditRecordView.as_view(), name='edit_record'),
    path('title/edit/', EditTitleView.as_view(), name='edit_title'),
]

house/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from house.models import House, Room, Device, Repair, Maintenance, MaintenanceEvent, Record, BaseName


generic_error = 'There was an error with your request. Please refresh the page and try again.'


class ContentTypeField(forms.Field):
    @staticmethod
    def get_content_type(value):
        object_types = {
            'house': House,
            'room': Room,
            'device': Device,
            'repair': Repair,
            'maintenance': Maintenance,
            'maintenanceEvent': MaintenanceEvent
        }
        return object_types.get(value)

    def to_python(self, value):
        return self.get_content_type(value)

    def validate(self, value):
        if not value:
            raise ValidationError(
                (generic_error),
                params={'value': value},
            )


class BaseObjectForm(forms.Form):
    name = forms.CharField(
        label='Name',
        widget=forms.TextInput,
        max_length=50,
        min_length=1)

    name.widget.attrs.update({
        'class': 'form-control'})

    date = forms.DateField(
        input_formats=['%m/%d/%Y'],
        widget=forms.DateInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )

    # date.widget.attrs.update({
    #     'class': 'input-group date col-sm-10',
    #     'id': 'datetimepicker1',
    #     'data-target-input': 'nearest'
    # })

    warrenty_length = forms.CharField(
        label='Warrenty Length',
        widget=forms.TextInput,
        max_length=150,
        min_length=1)

    warrenty_length.widget.attrs.update({
        'class': 'form-control',
        'placeholder': '1 Year'})

    cost = forms.IntegerField(
        label='Cost',
        widget=forms.NumberInput
    )

    cost.widget.attrs.update({
        'placeholder': '$100',
        'class': 'form-control'})

    notes = forms.CharField(
        label='Notes',
        widget=forms.Textarea,
        max_length=1000,
        min_length=1
    )

    notes.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Additional notes....'})


class AddDeviceForm(BaseObjectForm):
    field_order = ['name', 'date', 'cost', 'purchase_from', 'warrenty_length', 'notes']

    purchase_from = forms.CharField(
        label='Store',
        widget=forms.TextInput)

    purchase_from.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Amazon'})


class EditTitleForm(forms.ModelForm):
    object_type = ContentTypeField()
    object_id = forms.UUIDField()

    class Meta:
        model = BaseName
        fields = ['name', 'object_id', 'object_type']
        error_messages = {
            'name': {
                'max_length': ("Names are limited to 50 characters."),
                'required': 'A name is required.',
            },
            'object_id': {
                'invalid': generic_error
            }
        }


class AddRecordForm(forms.ModelForm):
    object_type = ContentTypeField()

    class Meta:
        model = Record
        fields = ['statement', 'response', 'object_id', 'object_type']
        error_messages = {
            'statement': {
                'max_length': ("Statments are limited to 150 characters."),
                'required': 'A statement is required for each record.',
            },
            'response': {
                'max_length': 'Responses are limited to 150 characters.'
            },
            'object_id': {
                'invalid': generic_error
            }
        }


class EditRecordForm(forms.ModelForm):
    record_id = forms.UUIDField()

    class Meta:
        model = Record
        fields = ['statement', 'response', 'record_id']
        error_messages = {
            'statement': {
                'max_length': ("Statments are limited to 150 characters."),
                'required': 'A statement is required for each record.',
            },
            'response': {
                'max_length': 'Responses are limited to 150 characters.'
            },
            'record_id': {
                'invalid': generic_error
            }
        }


class SignUpForm(forms.Form):
    def validate_password(value):
        if len(value) < 8:
            raise ValidationError(
                ('Password must be at least 8 characters long.'),
                params={'value': value},
            )

    def validate_email(email):
        e = User.objects.filter(email=email).exists()
        if e:
            raise ValidationError(
                ('That email has already been registered.'),
                params={'email': email},
            )

    email = forms.EmailField(
        label='Email',
        validators=[validate_email],
        widget=forms.EmailInput)

    password = forms.CharField(
        label='Password',
        max_length=100,
        validators=[validate_password],
        widget=forms.PasswordInput)

    email.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Email'})
    password.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Password'})

    def create_user(self):
        user = User.objects.create_user(
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'])
        House.objects.create(
            owner=user,
            name='Your House',
        )


class AuthForm(forms.Form):
    email = forms.CharField(
        label='Username/Email',
        widget=forms.TextInput)
    password = forms.CharField(
        label='Password',
        max_length=100,
        widget=forms.PasswordInput)

    email.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Username/Email'})
    password.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Password'})


class AddRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['name']
        error_messages = {
            'statement': {
                'max_length': ("Room names are limited to 50 characters."),
                'required': 'A name is required for each room.',
            }
        }

house/views/house.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core import serializers

from house.models import House, Record, Room
from house.forms import AddRoomForm
from house.utils import get_records


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/house.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        house = House.objects.filter(owner=self.request.user).first()
        data['house'] = house
        records = get_records(self.request.user, house.id, 'house')
        data['records'] = records
        return data

house/views/misc.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import FormView

from house.forms import EditTitleForm
from house.models import BaseName
from house.mixins import AjaxResponseMixin


class EditTitleView(AjaxResponseMixin, FormView):
    model = BaseName
    form_class = EditTitleForm

    def form_valid(self, form):
        print('did validate')
        try:
            object = get_object_or_404(
                form.cleaned_data['object_type'],
                pk=form.cleaned_data['object_id'],
                owner=self.request.user)
            object.name = form.cleaned_data['name']
            object.save()
            return HttpResponse(status=204)
        except:
            error_message = ['There was an error editing this name, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)

house/views/record.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView

from house.forms import AddRecordForm, EditRecordForm
from house.models import Record
from house.mixins import AjaxResponseMixin


# TODO: Find way to add LoginRequiredMixin back without redirect
class EditRecordView(AjaxResponseMixin, FormView):
    model = Record
    form_class = EditRecordForm

    def form_valid(self, form):
        try:
            r = get_object_or_404(
                Record,
                pk=form.cleaned_data['record_id'],
                owner=self.request.user)
        except:
            error_message = ['There was an error editing this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)
        r.statement = form.cleaned_data['statement']
        r.response = form.cleaned_data['response']
        r.save()
        return HttpResponse(status=204)


@login_required
def delete_record(request):
    if request.method == 'POST':
        record_id = request.POST.get('record_id')
        try:
            record = get_object_or_404(Record, owner=request.user, id=record_id)
            record.delete()
            return HttpResponse(status=204)
        except:
            error_message = [
                'There was an error deleting this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)


class AddRecordView(AjaxResponseMixin, FormView):
    model = Record
    form_class = AddRecordForm

    def form_valid(self, form):
        try:
            obj = get_object_or_404(
                form.cleaned_data['object_type'],
                pk=form.cleaned_data['object_id'],
                owner=self.request.user)
        except:
            error_message = [
                'There was an error creating this record, please refresh the page and try again.']
            return JsonResponse({'error': error_message}, status=400)
        record = Record.objects.create(
            owner=self.request.user,
            statement=form.cleaned_data['statement'],
            content_object=obj
        )
        if form.cleaned_data.get('response'):
            record.response = form.cleaned_data['response']
        record.save()
        data = {'id': record.id}
        return JsonResponse(data)

house/views/room.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.contenttypes.models import ContentType
# from django.contrib import messages

from house.models import House, Room, Repair, Device, Maintenance
from house.forms import AddRoomForm, AddDeviceForm
from house.utils import get_records

from itertools import chain


class RoomView(LoginRequiredMixin, TemplateView):
    template_name = 'house/page/room.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        room_id = self.kwargs.get('room_id')
        room = Room.objects.filter(owner=self.request.user, id=room_id).first()
        records = get_records(self.request.user, room.id, 'room')
        data['room'] = room
        data['records'] = records
        repairs = Repair.objects.filter(owner=self.request.user, room=room).order_by("date").all()
        devices = Device.objects.filter(owner=self.request.user, room=room).all()
        maintenance = Maintenance.objects.filter(owner=self.request.user, room=room).all()
        objects = list(chain(repairs, devices, maintenance))
        objects = sorted(objects, key=lambda o: o.date)
        data['objects'] = objects
        return data


class AddRoomView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/all_rooms.html'
    model = Room
    form_class = AddRoomForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        rooms = Room.objects.filter(owner=self.request.user).all()
        rooms.order_by('name')
        data['rooms'] = rooms
        return data

    def form_valid(self, form):
        name = form.cleaned_data['name']
        house = House.objects.filter(owner=self.request.user).first()
        r = Room.objects.create(name=name, house=house, owner=self.request.user)
        return redirect(reverse('house:room', args=[r.id]))


class AddPurchaseView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('house:login')
    template_name = 'house/page/new_device.html'
    model = Device
    form_class = AddDeviceForm

    def get_context_data(self, **kwargs):
        # TODO: handle case where no room is found
        data = super().get_context_data(**kwargs)
        room = Room.objects.filter(owner=self.request.user).filter(id=self.kwargs['room_id']).first()
        data['room'] = room
        return data

    def form_valid(self, form):
        print('valid form')
        room = Room.objects.filter(owner=self.request.user).filter(id=self.kwargs['room_id']).first()
        device = Device(name=form.cleaned_data['name'],
                        room=room,
                        date=form.cleaned_data['date'],
                        warrenty_length=form.cleaned_data['warrenty_length'],
                        cost=form.cleaned_data['cost'],
                        notes=form.cleaned_data['notes'],
                        owner=self.request.user)
        device.save()
        return redirect(reverse('house:room', args=[room.id]))

    def form_invalid(self, form):
        print('form invalid')
        print(form['date'])
        return super(AddPurchaseView, self).form_invalid(form)













#

house/views/user.py
from django.shortcuts import render
from django.views.generic import FormView, RedirectView
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

from house.forms import SignUpForm, AuthForm


class IndexView(FormView):
    template_name = 'house/page/index.html'
    form_class = SignUpForm
    success_url = reverse_lazy('house:house')

    def form_valid(self, form):
        form.create_user()
        user = User.objects.filter(email=form.cleaned_data['email']).first()
        login(self.request, user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'house/page/login.html'
    form_class = AuthForm
    success_url = reverse_lazy('house:house')

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('house:house'))
        else:
            form = AuthForm
            return render(request, 'house/page/login.html', {'form': form})

    def form_valid(self, form):
        username = form.cleaned_data['email']
        if '@' in form.cleaned_data['email']:
            user = User.objects.filter(
                email=form.cleaned_data['email']).first()
            username = user.username
        user = authenticate(
            username=username,
            password=form.cleaned_data['password'])
        if user is None:
            messages.info(self.request, 'Invalid email/password')
            return render(self.request, 'house/page/login.html', {'form': form})
        else:
            login(self.request, user)
            return super().form_valid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('house:login')

    def get(self, request):
        url = self.get_redirect_url()
        logout(request)
        messages.info(self.request, 'You have been logged out')
        return HttpResponseRedirect(url)

house/templates/house/page/house.html
{% extends "house/base.html" %}
{% load static %}


{% block title %} - House{% endblock %}

{% block page_title %}
    {% include "house/fragment/edit_title.html" with title=house.name id=house.id object_type='house' %}

{% endblock %}

{% block main %}
    <p>
        Welcome to your virtual house.  Start by adding rooms (Living Room, Kitchen, etc)
        to your virtual house so that it resembles your actual house. Then, you can
        start adding purchases, repairs, and routine maitinace to each room.
    </p>
    {% include "house/fragment/record.html" with object_id=house.id object_type='house' records=records %}
{% endblock %}

{% block extra_js %}
    <script src="{% static "js/record.js" %}"></script>
    <script>
        window.onpageshow = function() {
            build_table('{{records|safe}}');
            onCloseListener();
        };
    </script>
{% endblock %}

house/templates/house/page/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>BlueBoard</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/fa-all.min.css" %}">
    <link rel="stylesheet" href="{% static "css/pages/index.css" %}">
</head>

<body>

    {% include "house/fragment/signup_base.html" with sign_up=True %}

    <section class="features-icons bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="fas fa-tools m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Home Maintenance</h3>
                        <p class="lead mb-0">
                            Don't guess at when you last checked the smoke alarms or changed
                            the air conditioning filter.  Track all of it in one place and set
                            reminders for next time.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="fas fa-tv m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Item Warranties</h3>
                        <p class="lead mb-0">
                            Store all of your recipts and warrenty information in
                            one place so you will always know if your covered.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="fas fa-house-damage m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Home Repair</h3>
                        <p class="lead mb-0">
                            Always know who fixed it last, how much you paid, and what kind of warrenty they offer on their work.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="showcase">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url(&quot;{% static "img/bg-showcase-1.jpg" %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Easy to use</h2>
                    <p class="lead mb-0">Being an adult is hard enough without having to constantly rememeber if you paid the electric bill this month. &nbsp;Let us help you keep track of everything and remind you of upcoming tasks.</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image:url(&quot;{% static "img/bg-showcase-3.jpg" %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2><strong>Easy to Use &amp;&nbsp;Customize</strong></h2>
                    <p class="lead mb-0">Build a virtual house that mimics your real house so you can visualize everything that you need to do as well as everything you have done already.</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url(&quot;{% static "img/bg-showcase-2.jpg" %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2><strong>Completly Open Source</strong></h2>
                    <p class="lead mb-0">No one should have to sacrafice privacy for convenience. &nbsp;Blueboard is complely free of trackers and never sells your data. &nbsp;Don't belive us, feel free to thumb through the source code, or better yet, make a contribution.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="call-to-action text-white text-center" style="background:url(&quot;{% static "img/bg-masthead.jpg" %}&quot;) no-repeat center center;background-size:cover;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h2 class="mb-4">Ready to get started? Sign up now!</h2>
                </div>
                <div class="col-sm-6 offset-sm-3 text-center">
                    <div class="info-form">
                        <form method="POST" class="form-inlin justify-content-center">
                            {% for field in form %}
                                <div class="form-group">
                                    {{field}}
                                </div>
                            {% endfor %}
                            <button class="btn btn-primary" onclick="showToast()">Sign Up</button>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>


</body>

house/templates/house/page/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>BlueBoard</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/fa-all.min.css" %}">
    <link rel="stylesheet" href="{% static "css/pages/index.css" %}">
</head>

<body>

    {% include "house/fragment/signup_base.html" with sign_up=False %}

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>


</body>

house/templates/house/page/new_device.html
{% extends "house/base.html" %}
{% load static %}

{% block title %} - New Purchase{% endblock %}

{% block extra_css %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
{% endblock %}

{% block page_title %}
    {% include "house/fragment/basic_title.html" with title="New "|add:room.name|add:" Purchase" %}
{% endblock %}

{% block main %}
    {% include "house/fragment/event_form.html" with form=form %}

        
    </div>
</div>
{% endblock %}

{% block extra_js %}

{% endblock %}

house/templates/house/page/room.html
{% extends "house/base.html" %}
{% load static %}

{% block title %} - {{room.name}}{% endblock %}

{% block page_title %}
    {% include "house/fragment/edit_title.html" with title=room.name id=room.id object_type='room' %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/pages/room.css" %}">
    <link rel="stylesheet" href="{% static "css/fragments.css" %}">
{% endblock %}

{% block main %}
    {% if objects %}
    {% comment %}
    <div class="row">
        <h1 id="page-title">{{title}}</h1>
        <a href="#" class="mt-auto" data-toggle="modal" data-target="#edit-title-modal">
            <i class="far fa-edit edit-title-edit-icon"></i>
        </a>

    </div>
    {% endcomment %}
    <div class="container-fluid">
        <div class="row">
            <h4>Events</h4>
            <div class="dropdown show">
                <a class="dropdown-toggle" href="#" role="button" id="eventsDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="far fa-plus-square room-plus-icon"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="eventsDropDown">
                    <a class="dropdown-item" href="{% url 'house:new_device' room.id %}">Purchase</a>
                    <a class="dropdown-item" href="#">Repair</a>
                    <a class="dropdown-item" href="#">Maintenance</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="card-row">
        {% for object in objects %}
            {% include "house/fragment/card.html" with object=object %}
        {% endfor %}
    </div>
    {% else %}
        <p>
            Welcome! Start by adding some events or records.
        </p>
    {% endif %}

    {% include "house/fragment/record.html" with object_id=room.id object_type='room' records=records %}

{% endblock %}

{% block extra_js %}
    <script src="{% static "js/record.js" %}"></script>
    <script>
        window.onpageshow = function() {
            build_table('{{records|safe}}');
            onCloseListener();
        };
    </script>
{% endblock %}